apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-hydra-validator-client
data:
  start.sh: |-
    #!/bin/sh
    exec lighthouse vc \
              --testnet-dir=/data/testnet \
              --log-format=JSON \
              --datadir=/data \
              --unencrypted-http-transport \
    	      --init-slashing-protection \
              --http \
              --http-address=0.0.0.0 \
              --http-port=5062 \
              --metrics \
              --beacon-nodes="http://zeus-consensus-client:5052"
  download.sh: |-
    #!/bin/sh
    exec downloader --client-name="lighthouse" --workload-type="validatorClient" --protocol-network-id="${PROTOCOL_NETWORK_ID}" --cloud-provider="${CLOUD_PROVIDER}" --ctx="${CTX}" --ns="${NS}" --region="${REGION}"
  athena.sh: |-
    #!/bin/sh
    exec athena --protocol-network-id="${PROTOCOL_NETWORK_ID}" --cloud-provider="${CLOUD_PROVIDER}" --ctx="${CTX}" --ns="${NS}" --region="${REGION}"
