apiVersion: v1
kind: Service
metadata:
  name: zeus-hydra-validators
  labels:
    app.kubernetes.io/name: zeus-hydra-validators
    app.kubernetes.io/instance: zeus-hydra-validators
    app.kubernetes.io/managed-by: zeus-hydra-validators
spec:
  type: ClusterIP
  ports:
    - port: 9003
      targetPort: athena
      protocol: TCP
      name: athena
    - port: 5064
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: zeus-hydra-validators
    app.kubernetes.io/instance: zeus-hydra-validators
