apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zeus-hydra-validators-monitor
  labels:
    app: "zeus-hydra-validators"
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: "zeus-hydra-validators"
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
