apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zeus-hydra-validators
  labels:
    app.kubernetes.io/name: zeus-hydra-validators
    app.kubernetes.io/instance: zeus-hydra-validators
    app.kubernetes.io/managed-by: zeus
  annotations:
    {}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zeus-hydra-validators
      app.kubernetes.io/instance: zeus-hydra-validators
  serviceName: zeus-hydra-validators
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zeus-hydra-validators
        app.kubernetes.io/instance: zeus-hydra-validators
    spec:
      initContainers:
        - name: init-chown-data
          image: "busybox:1.34.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: [ "chown", "-R", "10001:10001", "/data" ]
          resources:
            { }
          volumeMounts:
            - name: hydra-validator-client-storage
              mountPath: "/data"
        - name: init-validator
          image: "registry.digitalocean.com/zeus-fyi/downloader:latest"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/download.sh" ]
          resources:
            {}
          volumeMounts:
            - name: cm-hydra-validator-client
              mountPath: "/scripts"
            - name: hydra-validator-client-storage
              mountPath: "/data"
      containers:
        - name: athena
          image: "registry.digitalocean.com/zeus-fyi/athena:latest"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/athena.sh" ]
          volumeMounts:
            - name: cm-hydra-validator-client
              mountPath: "/scripts"
            - name: hydra-validator-client-storage
              mountPath: "/data"
          ports:
            - name: athena
              containerPort: 9003
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 120
            tcpSocket:
              port: athena
        - name: zeus-hydra-validators
          image: "sigp/lighthouse:v3.3.0-modern"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/start.sh" ]
          volumeMounts:
            - name: cm-hydra-validator-client
              mountPath: "/scripts"
            - name: hydra-validator-client-storage
              mountPath: "/data"
          ports:
            - name: metrics
              containerPort: 5064
          resources:
            {}
          env:
            - name: PG_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: postgres-conn-str
            - name: AGE_PKEY
              valueFrom:
                secretKeyRef:
                  name: age-auth
                  key: age-private-key
            - name: DO_SPACES_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces-key
                  key: do-spaces-key
            - name: DO_SPACES_PKEY
              valueFrom:
                secretKeyRef:
                  name: spaces-auth
                  key: do-spaces-private-key
            - name: PROTOCOL_NETWORK_ID
              valueFrom:
                secretKeyRef:
                  name: workload
                  key: protocol-network-id
            - name: CLOUD_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: choreography
                  key: cloud-provider
            - name: CTX
              valueFrom:
                secretKeyRef:
                  name: choreography
                  key: ctx
            - name: NS
              valueFrom:
                secretKeyRef:
                  name: choreography
                  key: ns
            - name: REGION
              valueFrom:
                secretKeyRef:
                  name: choreography
                  key: region
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      volumes:
        - name: cm-hydra-validator-client
          configMap:
            name: cm-hydra-validator-client
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: hydra-validator-client-storage
        annotations:
          {}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "100Mi"


