version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'zeusfyi/redis:latest'
    command: redis-server --loadmodule /usr/local/lib/libredis_percentile.so --protected-mode no --bind 0.0.0.0 --maxmemory 1gb --maxmemory-policy volatile-lru
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/zeusfyi/redis/data
    ports:
      - '6381:6379'
    restart: unless-stopped

volumes:
  redis:
    driver: local