apiVersion: apps/v1
kind: Deployment
metadata:
  name: "iris"
  labels:
    app.kubernetes.io/instance: "iris"
    app.kubernetes.io/name: "iris"
spec:
  replicas: 8
  selector:
    matchLabels:
      app.kubernetes.io/name: "iris"
      app.kubernetes.io/instance: "iris"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "iris"
        app.kubernetes.io/instance: "iris"
    spec:
      initContainers:
        - name: init-aegis-secrets
          image: registry.digitalocean.com/zeus-fyi/aegis-secrets:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/secrets"
              name: "secrets"
      containers:
        - name: "iris"
          image: "registry.digitalocean.com/zeus-fyi/iris:latest"
          volumeMounts:
            - mountPath: "/secrets"
              name: "secrets"
            - mountPath: "/scripts"
              name: "cm-iris"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/start.sh" ]
          env:
            - name: AGE_PKEY
              valueFrom:
                secretKeyRef:
                  name: age-auth
                  key: age-private-key
            - name: DO_SPACES_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces-key
                  key: do-spaces-key
            - name: DO_SPACES_PKEY
              valueFrom:
                secretKeyRef:
                  name: spaces-auth
                  key: do-spaces-private-key
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
            - name: "metrics"
              containerPort: 9090
              protocol: "TCP"
          livenessProbe:
            httpGet:
              path: "/health"
              port: "http"
            failureThreshold: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: "/health"
              port: "http"
            failureThreshold: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 4Gi
      volumes:
        - name: secrets
          emptyDir:
            medium: Memory
        - name: cm-iris
          configMap:
            name: cm-iris
            defaultMode: 0744
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
