apiVersion: v1
kind: Service
metadata:
  name: "iris"
  labels:
    app.kubernetes.io/instance: "iris"
    app.kubernetes.io/name: "iris"
    app.kubernetes.io/managed-by: "zeus"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/instance: "iris"
    app.kubernetes.io/name: "iris"

