apiVersion: v1
kind: Service
metadata:
  name: zeus-tx-fetcher-nodeport
  labels:
    app.kubernetes.io/name: zeus-tx-fetcher
    app.kubernetes.io/instance: zeus-tx-fetcher
    app.kubernetes.io/managed-by: zeus
spec:
  type: LoadBalancer
  ports:
    - name: p2p-tcp
      port: 30303
      protocol: TCP
      targetPort: p2p-tcp
    - name: p2p-udp
      port: 30303
      protocol: UDP
      targetPort: p2p-udp
  selector:
    app.kubernetes.io/name: zeus-tx-fetcher
    app.kubernetes.io/instance: zeus-tx-fetcher
