apiVersion: v1
kind: Service
metadata:
  name: "anvil"
  labels:
    app.kubernetes.io/instance: "anvil"
    app.kubernetes.io/name: "anvil"
    app.kubernetes.io/managed-by: "zeus"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8545
      targetPort: http-rpc
      protocol: TCP
      name: http-rpc
    - port: 8888
      targetPort: hypnos
      protocol: TCP
      name: hypnos
    - port: 80
      targetPort: hypnos
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: "anvil"
    app.kubernetes.io/name: "anvil"
