apiVersion: source.toolkit.fluxcd.io/v2beta1
kind: HelmChart
metadata:
  name: flux-system
  namespace: flux-system
spec:
  chart: ./helm/eth-indexer
  sourceRef:
    name: flux-system
    namespace: flux-system
    kind: GitRepository
  interval: 10m
  reconcileStrategy: Revision