apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: eth-indexer
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: ssh://git@github.com/zeus-fyi/olympus
  ignore: |
    # exclude all
    /*
    # include eth-indexer helm chart directory
    !./helm/eth-indexer