apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-system
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm/eth-indexer
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3