apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eth-indexer
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm/eth-indexer
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: eth-indexer
        namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: eth-indexer
