apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eth-indexer
  namespace: eth-indexer
spec:
  chart:
    spec:
      chart: ./helm/eth-indexer
      sourceRef:
        kind: GitRepository
        name: eth-indexer
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3