apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eth-indexer
  namespace: eth-indexer
spec:
  chart:
    spec:
      chart: ./helm/eth-indexer
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: eth-indexer
        namespace: flux-system
      version: 0.1.0
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: eth-indexer
