apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eth-indexer
  namespace: eth-indexer
spec:
  releaseName: eth-indexer
  chart: ./helm/eth-indexer
  sourceRef:
    kind: GitRepository
    name: eth-indexer
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
