apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-hydra
data:
  start.sh: |-
    #!/bin/sh
    exec hydra --protocol-network-id=$(expr ${PROTOCOL_NETWORK_ID} + 0) --cloud-provider="${CLOUD_PROVIDER}" --ctx="${CTX}" --ns="${NS}" --region="${REGION}" --age-private-key="${AGE_PKEY}" --do-spaces-key="${DO_SPACES_KEY}" --do-spaces-private-key="${DO_SPACES_PKEY}" --env="production"