apiVersion: v1
kind: Service
metadata:
  name: "hydra"
  labels:
    app.kubernetes.io/instance: "hydra"
    app.kubernetes.io/name: "hydra"
    app.kubernetes.io/managed-by: "zeus"
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: "hydra"
    app.kubernetes.io/name: "hydra"

