apiVersion: v1
kind: Service
metadata:
  name: "zeus-hydra"
  labels:
    app: "zeus-hydra"
    app.kubernetes.io/instance: "zeus-hydra"
    app.kubernetes.io/name: "zeus-hydra"
    app.kubernetes.io/managed-by: "zeus"
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "zeus-hydra"
    app.kubernetes.io/instance: "zeus-hydra"
    app.kubernetes.io/name: "zeus-hydra"

