apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-monitor
  labels:
    app: "ingress-nginx"
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx  # This should match the labels of the NGINX Ingress Controller Service
  endpoints:
    - port: "metrics"
      interval: 10s
