apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eth-indexer"
  labels:
    app.kubernetes.io/instance: "eth-indexer"
    app.kubernetes.io/name: "eth-indexer"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "eth-indexer"
      app.kubernetes.io/instance: "eth-indexer"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "eth-indexer"
        app.kubernetes.io/instance: "eth-indexer"
    spec:
      containers:
        - name: "eth-indexer"
          image: "registry.digitalocean.com/zeus-fyi/zeus-indexer:latest"
          volumeMounts:
            - mountPath: "/scripts"
              name: "cm-eth-indexer"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/start.sh" ]
          env:
            - name: AGE_PKEY
              valueFrom:
                secretKeyRef:
                  name: age-auth
                  key: age-private-key
            - name: DO_SPACES_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces-key
                  key: do-spaces-key
            - name: DO_SPACES_PKEY
              valueFrom:
                secretKeyRef:
                  name: spaces-auth
                  key: do-spaces-private-key
          ports:
            - name: "http"
              containerPort: 9000
              protocol: "TCP"
          livenessProbe:
            httpGet:
              path: "/health"
              port: "http"
          readinessProbe:
            httpGet:
              path: "/health"
              port: "http"
          resources:
            {}
      volumes:
        - name: cm-eth-indexer
          configMap:
            name: cm-eth-indexer
            defaultMode: 0744
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
