apiVersion: v1
kind: Service
metadata:
  name: zeus-exec-client-nodeport
  labels:
    app.kubernetes.io/name: zeus-exec-client
    app.kubernetes.io/instance: zeus-exec-client
    app.kubernetes.io/managed-by: zeus
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 30303
      name: p2p-tcp
    - protocol: UDP
      port: 30303
      name: p2p-udp
  selector:
    app.kubernetes.io/name: zeus-exec-client
    app.kubernetes.io/instance: zeus-exec-client
