apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zeus-hydra-choreography-monitor
  labels:
    app: "zeus-hydra-choreography"
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "zeus-hydra-choreography"
      app.kubernetes.io/name: "zeus-hydra-choreography"
  endpoints:
    - port: http
      interval: 30s
      path: /metrics

