apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zeus-consensus-client
  labels:
    app: "zeus-consensus-client"
    app.kubernetes.io/name: zeus-consensus-client
    app.kubernetes.io/instance: zeus-consensus-client
    app.kubernetes.io/managed-by: zeus
  annotations:
    {}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: "zeus-consensus-client"
      app.kubernetes.io/name: zeus-consensus-client
      app.kubernetes.io/instance: zeus-consensus-client
  serviceName: zeus-consensus-client
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "zeus-consensus-client"
        app.kubernetes.io/name: zeus-consensus-client
        app.kubernetes.io/instance: zeus-consensus-client
    spec:
      initContainers:
        - name: init-chown-data
          image: "busybox:1.34.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "-R", "10001:10001", "/data"]
          resources:
            {}
          volumeMounts:
            - name: consensus-client-storage
              mountPath: "/data"
        - name: init-snapshots
          image: "registry.digitalocean.com/zeus-fyi/downloader:latest"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/download.sh" ]
          resources:
            {}
          volumeMounts:
            - name: cm-consensus-client
              mountPath: "/scripts"
            - name: consensus-client-storage
              mountPath: "/data"
      containers:
        - name: athena
          image: "registry.digitalocean.com/zeus-fyi/athena:latest"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/athena.sh" ]
          volumeMounts:
            - name: cm-consensus-client
              mountPath: "/scripts"
            - name: consensus-client-storage
              mountPath: "/data"
          ports:
            - name: athena
              containerPort: 9003
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 120
            tcpSocket:
              port: athena
        - name: zeus-consensus-client
          image: "sigp/lighthouse:capella"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/lighthouseEphemeral.sh" ]
          volumeMounts:
            - name: cm-consensus-client
              mountPath: "/scripts"
            - name: consensus-client-storage
              mountPath: "/data"
          ports:
            - name: p2p-tcp
              containerPort: 9000
              protocol: TCP
            - name: p2p-udp
              containerPort: 9000
              protocol: UDP
            - name: http-api
              containerPort: 5052
              protocol: TCP
            - name: metrics
              containerPort: 5054
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 120
            tcpSocket:
              port: http-api
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: http-api
          resources:
            {}
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      volumes:
        - name: cm-consensus-client
          configMap:
            name: cm-consensus-client
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: consensus-client-storage
        annotations:
          {}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "300Gi"


