apiVersion: v1
kind: Service
metadata:
  name: zeus-hydra-validators-1
  labels:
    app: "zeus-hydra-validators-1"
    app.kubernetes.io/name: zeus-hydra-validators-1
    app.kubernetes.io/instance: zeus-hydra-validators-1
    app.kubernetes.io/managed-by: zeus
spec:
  type: ClusterIP
  ports:
    - port: 9003
      targetPort: athena
      protocol: TCP
      name: athena
    - port: 5064
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: "zeus-hydra-validators-1"
    app.kubernetes.io/name: zeus-hydra-validators-1
    app.kubernetes.io/instance: zeus-hydra-validators-1
