apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zeus-hydra-validators-1
  labels:
    app: "zeus-hydra-validators-1"
    app.kubernetes.io/name: zeus-hydra-validators-1
    app.kubernetes.io/instance: zeus-hydra-validators-1
    app.kubernetes.io/managed-by: zeus
  annotations:
    {}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: "zeus-hydra-validators-1"
      app.kubernetes.io/name: zeus-hydra-validators-1
      app.kubernetes.io/instance: zeus-hydra-validators-1
  serviceName: zeus-hydra-validators-1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "zeus-hydra-validators-1"
        app.kubernetes.io/name: zeus-hydra-validators-1
        app.kubernetes.io/instance: zeus-hydra-validators-1
    spec:
      initContainers:
        - name: init-chown-data
          image: "busybox:1.34.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: [ "chown", "-R", "10001:10001", "/data" ]
          resources:
            { }
          volumeMounts:
            - name: hydra-validator-client-storage-1
              mountPath: "/data"
        - name: init-validators
          image: "registry.digitalocean.com/zeus-fyi/downloader:latest"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/download.sh" ]
          resources:
            {}
          volumeMounts:
            - name: cm-hydra-validator-client-1
              mountPath: "/scripts"
            - name: hydra-validator-client-storage-1
              mountPath: "/data"
      containers:
        - name: athena
          image: "registry.digitalocean.com/zeus-fyi/athena:latest"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/athena.sh" ]
          volumeMounts:
            - name: cm-hydra-validator-client-1
              mountPath: "/scripts"
            - name: hydra-validator-client-storage-1
              mountPath: "/data"
          ports:
            - name: athena
              containerPort: 9003
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 120
            tcpSocket:
              port: athena
        - name: zeus-hydra-validators
          image: "sigp/lighthouse:v3.5.1"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/start.sh" ]
          volumeMounts:
            - name: cm-hydra-validator-client-1
              mountPath: "/scripts"
            - name: hydra-validator-client-storage-1
              mountPath: "/data"
          ports:
            - name: metrics
              containerPort: 5064
          resources:
            {}
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      volumes:
        - name: cm-hydra-validator-client-1
          configMap:
            name: cm-hydra-validator-client-1
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: hydra-validator-client-storage-1
        annotations:
          {}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "4Gi"


