apiVersion: v1
kind: Service
metadata:
  name: zeus-web3signer
  labels:
    app.kubernetes.io/name: zeus-web3signer
    app.kubernetes.io/instance: zeus-web3signer
    app.kubernetes.io/managed-by: zeus-web3signer
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: zeus-web3signer
    app.kubernetes.io/instance: zeus-web3signer
