apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zeus-web3signer
  labels:
    app.kubernetes.io/name: zeus-web3signer
    app.kubernetes.io/instance: zeus-web3signer
    app.kubernetes.io/managed-by: zeus
  annotations:
    {}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zeus-web3signer
      app.kubernetes.io/instance: zeus-web3signer
  serviceName: zeus-web3signer
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zeus-web3signer
        app.kubernetes.io/instance: zeus-web3signer
    spec:
      containers:
        - name: zeus-web3signer
          image: "registry.digitalocean.com/zeus-fyi/web3signer:latest"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/start.sh" ]
          volumeMounts:
            - name: cm-web3signer
              mountPath: "/scripts"
            - name: web3signer-storage
              mountPath: "/data"
          ports:
            - name: http
              containerPort: 9000
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 120
            tcpSocket:
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: http
          resources:
            {}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: web3signer
                  key: postgres-db
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: web3signer
                  key: postgres-username
            - name: POSTGRES_AUTH
              valueFrom:
                secretKeyRef:
                  name: web3signer
                  key: postgres-auth
            - name: NETWORK
              valueFrom:
                secretKeyRef:
                  name: web3signer
                  key: network
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      volumes:
        - name: cm-web3signer
          configMap:
            name: cm-web3signer
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: web3signer-storage
        annotations:
          {}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "100Mi"


