apiVersion: apps/v1
kind: Deployment
metadata:
  name: "pandora"
  labels:
    app.kubernetes.io/instance: "pandora"
    app.kubernetes.io/name: "pandora"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "pandora"
      app.kubernetes.io/instance: "pandora"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "pandora"
        app.kubernetes.io/instance: "pandora"
    spec:
      imagePullSecrets:
        - name: zeus-fyi-ext
      containers:
        - name: "pandora"
          image: "registry.digitalocean.com/zeus-fyi/pandora:latest"
          imagePullPolicy: Always
          env:
            - name: TELEGRAM_API_HASH
              value: "badbaaafe1303acc5f3a6eb6c5cd3d39"
            - name: TELEGRAM_API_ID
              value: "24109712"
          ports:
            - name: "http"
              containerPort: 8000
              protocol: "TCP"
          livenessProbe:
            httpGet:
              path: "/health"
              port: "http"
            failureThreshold: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: "http"
            initialDelaySeconds: 20
            failureThreshold: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            {}
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
