apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-hephaestus
data:
  start.sh: |-
    #!/bin/sh
    exec hephaestus --age-private-key="${AGE_PKEY}" --do-spaces-key="${DO_SPACES_KEY}" --do-spaces-private-key="${DO_SPACES_PKEY}" --env="production"