apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-geth
data:
  start.sh: |-
    #!/bin/sh
    create_jwt_then_start { 
      echo "9492b672e33d2ce17026be9c678069e3bca9b671e26066b63414642036775895" > /data/jwt.hex
      geth
      --datadir=/data \
      --port=30303 \
      --http \
      --http.addr=0.0.0.0 \
      --http.port=8545 \
      --http.vhosts=* \
      --http.corsdomain=* \
      --ws \
      --ws.addr=0.0.0.0 \
      --ws.port=8546 \
      --ws.origins=* \
      --authrpc.jwtsecret=/data/jwt.hex \
      --authrpc.addr=0.0.0.0 \
      --authrpc.port=8551 \
      --authrpc.vhosts=* 
    }
    exec create_jwt_then_start
