apiVersion: v1
data:
    beacon-conn-str: ENC[AES256_GCM,data:gV72S7C59gzBd0K5emkw1vO4JXbM0g2ewwxp5lFU18A5j6x2MgkBjCwLkx9TGW8ENjtgmoGnX8lr0mDMhq9R/0kQRmMfIanmJP7RGUA7HikfE/ZQjvnTmQ==,iv:4XTkAU01a6nWDuzLtcCmifk5FN6j+AAvZSPeXbOmkKc=,tag:U+102sOXp5mIEMWagv820Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: beacon-auth
    namespace: eth-indexer
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14h7yvfgkcdat8kdk2wl7gmxjw6a9j32yn2zhz2e4fgercv5gnf0s4svmu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbEdqdnRJRXJ1RFlldDh1
            N1o1ZnVwb3FUUk5EWTNQYzA1WEo2bmxPdWc4CmJtK0lBVGVqdW9EY0ZrWCsvMWxG
            VlB5bnVmQXl0S2xqcm42UW5XRktLM0kKLS0tIFlMcmRVL0lKOGRENWpFUThsUEFQ
            MEZ6WERNTlRqQlpMS2t6WlhOVis3ckkKDFxJr7QPXgtqRyt8fCZ18ye7cvHBgjLQ
            rJ+rTZf5uRViz015ZwFYz0g0hQMuSymfmGZ1flWUQYj8dflAs0RvAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-25T05:57:37Z"
    mac: ENC[AES256_GCM,data:p4oC9IOSHUhjumGfkt+/IhncJy6m7IzF9mzXGvBgAcbMUmmTqO/fhiER3kxZDZ5LvF0C3aM/4v7mvWVe4g/V+jcRJqcZ4LStWalxXv8y8Y3f/zBH9v0MrxuECn+FxHJuGj79J7H+wZ6bcVpIF3llkSM8ZA01FyagioYaPsT7IEQ=,iv:eEZbehhvY37ezELfkECiCMgKSYr4KSzjzHSdnGjB4gU=,tag:+2np9Jid2K3RSJzP8iLE2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
