apiVersion: v1
data:
    postgres-conn-str: ENC[AES256_GCM,data:Gq2yZ7J2qKWnF09XYzzDWJYfhbQaiCtIJKBamjdfhiLzdOj71hoDhTjIvbe3gKYzqTLKECJFFdh39APyuWG7TTZBLaUaHRfwHoddX3Me9JgD8jzR4CqZftMRN4J+lbFJKQA/NghHBTcb/6heKHdA8NXn2sLJEQmyG9SJyKt8Tbjo5tbe+eAkW4Ol/k8/P7X+6ndEfabPj6KqluVjKKqeSrqTZhIicVH1Tjh3Nvt3eo8RBvQErTgOysiQJk0yVhsMjdYrVeQPO4L5Cpis7hLXeEWQVwMUd4arflisvHXn/TDoWw1L5xlrmjZ7d99Y2OsJ4+PEr5kSX8I1GwqFoX/7c3D9+fKZ5F9INoF/zvHJI0G2vHZ0Ald8mk3ScquC/3/1o9LuF7b5K5Q=,iv:fhPpofmbR21mtBj0gKSuQnwjJr1lqAJGRONIjnEPGsc=,tag:iPnTQ/2tVktbXWtlXA17kQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: postgres-auth
    namespace: eth-indexer
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-17T05:41:22Z"
    mac: ENC[AES256_GCM,data:yUhZDl5Zzp9VzrKyDw93tLYuACNezf91QDMT90vLsceCh6IYOQUec5MiaPD0hCr84dlX4g4aLvP/hWp+7lJOoaBt6VQI4hxaf/wt93mHcFi7w5sLgkeak0Pz1WS6X/hLYhyJADmm/6/QH4mdfjon9ELUw1JOkddGflmCqcFrR5Q=,iv:u4nAmnY7JhRQBcZZEi+a9/ZOB/kJNida4/ZOigA6FnQ=,tag:JNwBw7NGXjXlGoXhuvnInQ==,type:str]
    pgp:
        - created_at: "2022-07-17T05:41:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DoBxvd+FtCAoSAQdACQTfwZ1uSkrOm0nIlf8vhqTE0QMhDI0MaNQ6Wx6WCTIw
            yxTILMlYvHNm9ZEOwKgxLD9Dy2Xuz7Q9OXNtDG8lw1Uj9bwpqs+722DMdeufF0Rz
            1GgBCQIQriAvOlfBQWXWYSHhnkt+bYLapvHX0u9X5FTDMKqkIntXm5xNxp3AlX0Q
            QmOTxzz6iGfBRewVEfgLo23kPh/VnoSEt0bkEZqfzz/Wykyb0XjxF3bTsdlOyfSV
            2VC269/gmXb+xA==
            =I0K9
            -----END PGP MESSAGE-----
          fp: 7C417BF72F7500DBE82B5C5269090D0D4093C215
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
