apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-tx-fetcher
data:
  start.sh: |-
    #!/bin/sh
    exec geth \
      --datadir=/data \
      --port=30303 \
      --http \
      --http.addr=0.0.0.0 \
      --http.port=8545 \
      --http.vhosts=* \
      --http.corsdomain=* \
      --ws \
      --ws.addr=0.0.0.0 \
      --ws.port=8546 \
      --ws.origins=* \
      --metrics \
      --metrics.addr=0.0.0.0 \
      --metrics.port=6060 \
      --authrpc.jwtsecret=/data/jwt.hex \
      --authrpc.addr=0.0.0.0 \
      --authrpc.port=8551 \
      --authrpc.vhosts=* \
      --http.api=txpool,eth,net,web3,txpool \
      --txpool.globalqueue=0 \
      --txpool.accountqueue=0 \
      --txpool.globalslots=10000 \
      --txpool.pricelimit 15 \
      --maxpeers=100 \
      --syncmode=disabled \
      --dynamodb-access-key="${DYNAMODB_ACCESS_KEY}" \
      --dynamodb-secret-key="${DYNAMODB_SECRET_KEY}" \
      --postgres-conn-str="${PG_CONN_STR}"