apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zeus-tx-fetcher-monitor
  labels:
    app: "zeus-tx-fetcher"
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "zeus-tx-fetcher"
      app.kubernetes.io/name: "zeus-tx-fetcher"
  endpoints:
    - port: metrics
      interval: 30s
      path: /debug/metrics/prometheus
  metricRelabelings:
    - sourceLabels: [__name__]
      regex: "(txpool_invalid|txpool_unique)"
      action: keep