apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zeus-cloud"
  labels:
    app.kubernetes.io/instance: "zeus-cloud"
    app.kubernetes.io/name: "zeus-cloud"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "zeus-cloud"
      app.kubernetes.io/instance: "zeus-cloud"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "zeus-cloud"
        app.kubernetes.io/instance: "zeus-cloud"
    spec:
      containers:
        - name: "tokenizer"
          image: "registry.digitalocean.com/zeus-fyi/tokenizer:latest"
          imagePullPolicy: Always
          ports:
            - name: "http-api"
              containerPort: 5001
              protocol: "TCP"
          resources:
            {}
        - name: "zeus-cloud"
          image: "registry.digitalocean.com/zeus-fyi/zeus-cloud:latest"
          imagePullPolicy: Always
          env:
            - name: REACT_APP_BACKEND_ENDPOINT
              value: "http://hestia.hestia.svc.cluster.local:9002"
            - name: REACT_APP_ZEUS_BACKEND_ENDPOINT
              value: "http://zeus.zeus.svc.cluster.local:9001"
            - name: REACT_APP_ARTEMIS_BACKEND_ENDPOINT
              value: "http://artemis.artemis.svc.cluster.local:9004"
          ports:
            - name: "http"
              containerPort: 3000
              protocol: "TCP"
          resources:
            {}
      volumes:
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
