apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-p2p-crawler
data:
  athena.sh: |-
    #!/bin/sh 
    exec athena --workload-type="p2pCrawler" --protocol-network-id=0 --age-private-key="${AGE_PKEY}" --do-spaces-key="${DO_SPACES_KEY}" --do-spaces-private-key="${DO_SPACES_PKEY}" --env="production" --cloud-provider="${CLOUD_PROVIDER}" --ctx="${CTX}" --ns="${NS}" --region="${REGION}"
