apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zeus-hydra
    app.kubernetes.io/instance: zeus-hydra
    app.kubernetes.io/managed-by: zeus
    app.kubernetes.io/name: zeus-hydra
  name: zeus-hydra
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: http
  selector:
    app: zeus-hydra
    app.kubernetes.io/instance: zeus-hydra
    app.kubernetes.io/name: zeus-hydra
  type: ClusterIP
status:
  loadBalancer: {}
