apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zeus"
  labels:
    app.kubernetes.io/instance: "zeus"
    app.kubernetes.io/name: "zeus"
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: "zeus"
      app.kubernetes.io/instance: "zeus"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "zeus"
        app.kubernetes.io/instance: "zeus"
    spec:
      containers:
        - name: "zeus"
          image: "registry.digitalocean.com/zeus-fyi/zeus:latest"
          volumeMounts:
            - mountPath: "/scripts"
              name: "cm-zeus"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/start.sh" ]
          env:
            - name: PG_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: postgres-conn-str
            - name: AGE_PKEY
              valueFrom:
                secretKeyRef:
                  name: age-auth
                  key: age-private-key
            - name: DO_SPACES_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces-key
                  key: do-spaces-key
            - name: DO_SPACES_PKEY
              valueFrom:
                secretKeyRef:
                  name: spaces-auth
                  key: do-spaces-private-key
          ports:
            - name: "http"
              containerPort: 9001
              protocol: "TCP"
          livenessProbe:
            httpGet:
              path: "/health"
              port: "http"
          readinessProbe:
            httpGet:
              path: "/health"
              port: "http"
          resources:
            {}
      volumes:
        - name: cm-zeus
          configMap:
            name: cm-zeus
            defaultMode: 0744
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
