apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-redis-replicas
data:
  start.sh: |-
    #!/bin/sh
    exec redis-server --protected-mode no --bind 0.0.0.0 --dir /data --maxmemory 27gb --maxmemory-policy volatile-lru --slaveof "redis-master.redis.svc.cluster.local" 6379