apiVersion: apps/v1
kind: Deployment
metadata:
  name: "redis-replicas"
  labels:
    app.kubernetes.io/instance: "redis-replicas"
    app.kubernetes.io/name: "redis-replicas"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: "redis-replicas"
      app.kubernetes.io/instance: "redis-replicas"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "redis-replicas"
        app.kubernetes.io/instance: "redis-replicas"
    spec:
      containers:
        - name: "redis-replicas"
          image: "redis:7.0.12"
          volumeMounts:
            - mountPath: "/scripts"
              name: "cm-redis-replicas"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/start.sh" ]
          ports:
            - name: "redis"
              containerPort: 6379
              protocol: "TCP"
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 3
          resources:
            {}
      volumes:
        - name: cm-redis-replicas
          configMap:
            name: cm-redis-replicas
            defaultMode: 0744
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
