apiVersion: v1
kind: Service
metadata:
  name: "redis-replicas"
  labels:
    app.kubernetes.io/instance: "redis-replicas"
    app.kubernetes.io/name: "redis-replicas"
    app.kubernetes.io/managed-by: "zeus"
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/instance: "redis-replicas"
    app.kubernetes.io/name: "redis-replicas"

