BEGIN;
INSERT INTO "public"."chart_component_resources" VALUES (0, 'Deployment', 'apps/v1');
INSERT INTO "public"."chart_component_resources" VALUES (1, 'StatefulSet', 'apps/v1');
INSERT INTO "public"."chart_component_resources" VALUES (2, 'Service', 'v1');
INSERT INTO "public"."chart_component_resources" VALUES (3, 'Pod', 'v1');
INSERT INTO "public"."chart_component_resources" VALUES (4, 'ReplicaSet', 'apps/v1');
INSERT INTO "public"."chart_component_resources" VALUES (5, 'DaemonSet', 'apps/v1');
INSERT INTO "public"."chart_component_resources" VALUES (6, 'Job', 'batch/v1');
INSERT INTO "public"."chart_component_resources" VALUES (7, 'CronJob', 'batch/v1');
INSERT INTO "public"."chart_component_resources" VALUES (8, 'ReplicationController', 'v1');
INSERT INTO "public"."chart_component_resources" VALUES (9, 'PersistentVolumeClaim', 'v1');
INSERT INTO "public"."chart_component_resources" VALUES (10, 'PersistentVolume', 'v1');
INSERT INTO "public"."chart_component_resources" VALUES (11, 'StorageClass', 'storage.k8s.io/v1');
INSERT INTO "public"."chart_component_resources" VALUES (12, 'ConfigMap', 'v1');
INSERT INTO "public"."chart_component_resources" VALUES (13, 'Secret', 'v1');
INSERT INTO "public"."chart_component_resources" VALUES (14, 'Ingress', 'networking.k8s.io/v1');
INSERT INTO "public"."chart_component_resources" VALUES (15, 'IngressClass', 'networking.k8s.io/v1');
INSERT INTO "public"."chart_component_resources" VALUES (16, 'VolumeSnapshotContent', 'snapshot.storage.k8s.io/v1');
INSERT INTO "public"."chart_component_resources" VALUES (17, 'ServiceAccount', 'v1');
INSERT INTO "public"."chart_component_resources" VALUES (18, 'ClusterRole', 'rbac.authorization.k8s.io/v1');
INSERT INTO "public"."chart_component_resources" VALUES (19, 'RoleBinding', 'rbac.authorization.k8s.io/v1');
INSERT INTO "public"."chart_component_resources" VALUES (20, 'ClusterRoleBinding', 'rbac.authorization.k8s.io/v1');
INSERT INTO "public"."chart_component_resources" VALUES (21, 'Role', 'rbac.authorization.k8s.io/v1');
INSERT INTO "public"."chart_component_resources" VALUES (22, 'CSIDriver', 'storage.k8s.io/v1');
INSERT INTO "public"."chart_component_resources" VALUES (23, 'CSINode', 'storage.k8s.io/v1');
INSERT INTO "public"."chart_component_resources" VALUES (24, 'CSIStorageCapacity', 'storage.k8s.io/v1');
COMMIT;