apiVersion: apps/v1
kind: Deployment
metadata:
  name: "redis-master"
  labels:
    app.kubernetes.io/instance: "redis-master"
    app.kubernetes.io/name: "redis-master"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "redis-master"
      app.kubernetes.io/instance: "redis-master"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "redis-master"
        app.kubernetes.io/instance: "redis-master"
    spec:
      containers:
        - name: "redis-master"
          image: "redis:7.0.12"
          volumeMounts:
            - mountPath: "/scripts"
              name: "cm-redis-master"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/start.sh" ]
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          livenessProbe:
            httpGet:
              path: "/health"
              port: "http"
            failureThreshold: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: "/health"
              port: "http"
            failureThreshold: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            {}
      volumes:
        - name: cm-redis-master
          configMap:
            name: cm-redis-master
            defaultMode: 0744
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
