apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-exec-client
data:
  start.sh: |-
    #!/bin/sh
    exec geth \
      --datadir=/data \
      --port=30303 \
      --http \
      --http.addr=0.0.0.0 \
      --http.port=8545 \
      --http.vhosts=* \
      --http.corsdomain=* \
      --ws \
      --ws.addr=0.0.0.0 \
      --ws.port=8546 \
      --ws.origins=* \
      --authrpc.jwtsecret=/data/jwt.hex \
      --authrpc.addr=0.0.0.0 \
      --authrpc.port=8551 \
      --authrpc.vhosts=* \
      --http.api=txpool,eth,net,web3,txpool \
      --txpool.globalqueue=0 \
      --txpool.accountqueue=0 \
      --txpool.globalslots=10000 \
      --txpool.pricelimit 50 \
      --maxpeers=100
  download.sh: |-
    #!/bin/sh
    exec downloader --workload-type="beaconExecClient" --client-name="geth" --protocol-network-id=${PROTOCOL_NETWORK_ID} --age-private-key="${AGE_PKEY}" --do-spaces-key="${DO_SPACES_KEY}" --do-spaces-private-key="${DO_SPACES_PKEY}" --env="production" --cloud-provider="${CLOUD_PROVIDER}" --ctx="${CTX}" --ns="${NS}" --region="${REGION}"
  geth.sh: |-
    #!/bin/sh
    exec geth \
      --datadir=/data \
      --port=30303 \
      --http \
      --http.addr=0.0.0.0 \
      --http.port=8545 \
      --http.vhosts=* \
      --http.corsdomain=* \
      --ws \
      --ws.addr=0.0.0.0 \
      --ws.port=8546 \
      --ws.origins=* \
      --authrpc.jwtsecret=/data/jwt.hex \
      --authrpc.addr=0.0.0.0 \
      --authrpc.port=8551 \
      --authrpc.vhosts=* \
      --http.api=txpool,eth,net,web3,txpool \
      --txpool.globalqueue=0 \
      --txpool.accountqueue=0 \
      --txpool.globalslots=10000 \
      --txpool.pricelimit 50 \
      --maxpeers=100
  gethGoerli.sh: |-
    #!/bin/sh
    exec geth \
      --datadir=/data \
      --port=30303 \
      --http \
      --http.addr=0.0.0.0 \
      --http.port=8545 \
      --http.vhosts=* \
      --http.corsdomain=* \
      --ws \
      --ws.addr=0.0.0.0 \
      --ws.port=8546 \
      --ws.origins=* \
      --authrpc.jwtsecret=/data/jwt.hex \
      --authrpc.addr=0.0.0.0 \
      --authrpc.port=8551 \
      --authrpc.vhosts=* \
      --rpc.gascap=0 \
      --rpc.txfeecap=0 \
      --goerli
  athena.sh: |-
    #!/bin/sh 
    exec athena --workload-type="beaconExecClient" --protocol-network-id=${PROTOCOL_NETWORK_ID} --age-private-key="${AGE_PKEY}" --do-spaces-key="${DO_SPACES_KEY}" --do-spaces-private-key="${DO_SPACES_PKEY}" --env="production" --cloud-provider="${CLOUD_PROVIDER}" --ctx="${CTX}" --ns="${NS}" --region="${REGION}"
  gethEphemery.sh: |-
    #!/bin/sh
    exec geth \
      --datadir=/data \
      --port=30303 \
      --http \
      --http.addr=0.0.0.0 \
      --http.port=8545 \
      --http.vhosts=* \
      --http.corsdomain=* \
      --ws \
      --ws.addr=0.0.0.0 \
      --ws.port=8546 \
      --ws.origins=* \
      --authrpc.jwtsecret=/data/jwt.hex \
      --authrpc.addr=0.0.0.0 \
      --authrpc.port=8551 \
      --authrpc.vhosts=* \
      --rpc.gascap=0 \
      --rpc.txfeecap=0 \
      --networkid=$(grep CHAIN_ID /data/nodevars_env.txt | cut -d '=' -f 2 | tr -d '"') \
      --bootnodes=enode://0f2c301a9a3f9fa2ccfa362b79552c052905d8c2982f707f46cd29ece5a9e1c14ecd06f4ac951b228f059a43c6284a1a14fce709e8976cac93b50345218bf2e9@135.181.140.168:30343
