apiVersion: apps/v1
kind: Deployment
metadata:
  name: "demo"
  labels:
    app.kubernetes.io/instance: "demo"
    app.kubernetes.io/name: "demo"
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: "demo"
      app.kubernetes.io/instance: "demo"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "demo"
        app.kubernetes.io/instance: "demo"
    spec:
      containers:
        - name: "demo"
          image: "docker.io/hashicorp/http-echo:latest"
          volumeMounts:
            - mountPath: "/scripts"
              name: "cm-demo"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/start.sh" ]
          ports:
            - name: "http"
              containerPort: 5678
              protocol: "TCP"
          livenessProbe:
            httpGet:
              path: "/health"
              port: "http"
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: "/health"
              port: "http"
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            {}
      volumes:
        - name: cm-demo
          configMap:
            name: cm-demo
            defaultMode: 0744
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
