apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tyche-monitor
  labels:
    app: "tyche"
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "tyche"
      app.kubernetes.io/name: "tyche"
  endpoints:
    - port: http
      interval: 30s
      path: /metrics

