/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type BlockRequestCapella struct {
	// version to identify block request type.
	Version string `json:"version"`

	BlockHeader BeaconBlockHeader `json:"block_header"`
}
