/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type BlockRequestPhase0 struct {

	// version to identify block request type.
	Version string `json:"version"`

	Block BeaconBlock `json:"block"`
}
