/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type BeaconBlockAltair struct {
	Slot string `json:"slot,omitempty"`

	ProposerIndex string `json:"proposer_index,omitempty"`

	ParentRoot string `json:"parent_root,omitempty"`

	StateRoot string `json:"state_root,omitempty"`

	Body BeaconBlockBodyAltair `json:"body,omitempty"`
}
