/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type RandaoRevealSigning struct {
	Type string `json:"type"`

	ForkInfo SigningForkInfo `json:"fork_info"`

	SigningRoot string `json:"signingRoot,omitempty"`

	RandaoReveal RandaoReveal `json:"randao_reveal"`
}
