/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type SyncCommitteeMessage struct {

	// Bytes32 hexadecimal
	BeaconBlockRoot string `json:"beacon_block_root,omitempty"`

	Slot string `json:"slot,omitempty"`
}
