/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type ListKeysResponseData struct {

	// The validator's BLS public key, uniquely identifying them. _48-bytes, hex encoded with 0x prefix, case insensitive._
	ValidatingPubkey string `json:"validating_pubkey"`

	// The derivation path (if present in the imported keystore).
	DerivationPath string `json:"derivation_path,omitempty"`

	// The key associated with this pubkey cannot be deleted from the API
	Readonly bool `json:"readonly,omitempty"`
}
