/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type BeaconBlockHeader struct {
	Slot string `json:"slot,omitempty"`

	ProposerIndex string `json:"proposer_index,omitempty"`

	// Bytes32 hexadecimal
	ParentRoot string `json:"parent_root,omitempty"`

	// Bytes32 hexadecimal
	StateRoot string `json:"state_root,omitempty"`

	// Bytes32 hexadecimal
	BodyRoot string `json:"body_root,omitempty"`
}
