/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type DepositSigningDeposit struct {
	Pubkey string `json:"pubkey,omitempty"`

	WithdrawalCredentials string `json:"withdrawal_credentials,omitempty"`

	Amount string `json:"amount,omitempty"`

	// Bytes4 hexadecimal
	GenesisForkVersion string `json:"genesis_fork_version,omitempty"`
}
