/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type DepositData struct {
	Pubkey string `json:"pubkey,omitempty"`

	WithdrawalCredentials string `json:"withdrawal_credentials,omitempty"`

	Amount string `json:"amount,omitempty"`

	Signature string `json:"signature,omitempty"`
}
