/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type Fork struct {
	PreviousVersion string `json:"previous_version,omitempty"`

	CurrentVersion string `json:"current_version,omitempty"`

	Epoch string `json:"epoch,omitempty"`
}
