/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type AttestationData struct {
	Slot string `json:"slot,omitempty"`

	Index string `json:"index,omitempty"`

	BeaconBlockRoot string `json:"beacon_block_root,omitempty"`

	Source Checkpoint `json:"source,omitempty"`

	Target Checkpoint `json:"target,omitempty"`
}
