/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type AttesterSlashing struct {
	Attestation1 IndexedAttestation `json:"attestation_1,omitempty"`

	Attestation2 IndexedAttestation `json:"attestation_2,omitempty"`
}
