/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type Eth1Data struct {
	DepositRoot string `json:"deposit_root,omitempty"`

	DepositCount string `json:"deposit_count,omitempty"`

	BlockHash string `json:"block_hash,omitempty"`
}
