/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type ImportKeystoresResponse struct {

	// Status result of each `request.keystores` with same length and order of `request.keystores`
	Data []ImportKeystoresResponseData `json:"data"`
}
