/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type SyncAggregate struct {

	// SSZ hexadecimal
	SyncCommitteeBits string `json:"sync_committee_bits,omitempty"`

	// Bytes96 hexadecimal
	SyncCommitteeSignature string `json:"sync_committee_signature,omitempty"`
}
