/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type DeleteKeysResponse struct {

	// Deletion status of all keys in `request.pubkeys` in the same order.
	Data []DeleteKeysResponseData `json:"data"`

	// JSON serialized representation of the slash protection data in format defined in EIP-3076: Slashing Protection Interchange Format.
	SlashingProtection string `json:"slashing_protection"`
}
