/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type InlineObject struct {

	// JSON-encoded keystore files generated with the Launchpad.
	Keystores []string `json:"keystores"`

	// Passwords to unlock imported keystore files. `passwords[i]` must unlock `keystores[i]`.
	Passwords []string `json:"passwords"`

	// JSON serialized representation of the slash protection data in format defined in EIP-3076: Slashing Protection Interchange Format.
	SlashingProtection string `json:"slashing_protection,omitempty"`
}
