/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type DeleteKeysResponseData struct {

	// - deleted: key was active and removed - not_active: slashing protection data returned but key was not active - not_found: key was not found to be removed, and no slashing data can be returned - error: unexpected condition meant the key could not be removed (the key was actually found, but we couldn't stop using it) - this would be a sign that making it active elsewhere would almost certainly cause you headaches / slashing conditions etc.
	Status string `json:"status"`

	// error message if status == error
	Message string `json:"message,omitempty"`
}
