/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type VoluntaryExit struct {
	Epoch string `json:"epoch,omitempty"`

	ValidatorIndex string `json:"validator_index,omitempty"`
}
