/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type ValidatorRegistration struct {

	// Bytes20 hexadecimal
	FeeRecipient string `json:"fee_recipient,omitempty"`

	GasLimit string `json:"gas_limit,omitempty"`

	Timestamp string `json:"timestamp,omitempty"`

	Pubkey string `json:"pubkey,omitempty"`
}
