/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type ContributionAndProof struct {
	AggregatorIndex string `json:"aggregator_index,omitempty"`

	// Bytes96 hexadecimal
	SelectionProof string `json:"selection_proof,omitempty"`

	Contribution SyncCommitteeContribution `json:"contribution,omitempty"`
}
