/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type BeaconBlockBodyAltair struct {
	RandaoReveal string `json:"randao_reveal,omitempty"`

	Eth1Data Eth1Data `json:"eth1_data,omitempty"`

	// Bytes32 hexadecimal
	Graffiti string `json:"graffiti,omitempty"`

	ProposerSlashings []ProposerSlashing `json:"proposer_slashings,omitempty"`

	AttesterSlashings []AttesterSlashing `json:"attester_slashings,omitempty"`

	Attestations []Attestation `json:"attestations,omitempty"`

	Deposits []Deposit `json:"deposits,omitempty"`

	VoluntaryExits []SignedVoluntaryExit `json:"voluntary_exits,omitempty"`

	SyncAggregate SyncAggregate `json:"sync_aggregate,omitempty"`
}
