/*
 * Web3Signer ETH2 Api
 *
 * Sign Eth2 Artifacts
 *
 * API version: @VERSION@
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consensys_eth2_openapi

type InlineResponse2001 struct {

	// health status
	Status string `json:"status,omitempty"`

	// list of status checks
	Checks []map[string]interface{} `json:"checks,omitempty"`

	// the overall outcome of health check
	Outcome string `json:"outcome,omitempty"`
}
