apiVersion: v1
data:
    beacon-conn-str: ENC[AES256_GCM,data:SD7w1XnU2NQzRt288teLdR/H+KBz285VWRUUTxuMYJ7YUd5xxKsKbA76DMRWkZ0mNV2jsZ/V81OmRXBcxcxfzFqUXdZZ+vq6PoGCvEaAYvoGbDB2JvfathLQ/vj0A4opU9iA/9dXVwXOmy0nDhHh04Q8ganP+2IGgQM1kJZnthRZEfo0p5qj6qB7agQ=,iv:1eTmrZC2mpzrPm+izc7XpGFUvFJUnTGkgz8WdDXRgj4=,tag:ZnIkpGEDc7GpERvvF1SKvQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: beacon-dev-auth
    namespace: eth-indexer
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14h7yvfgkcdat8kdk2wl7gmxjw6a9j32yn2zhz2e4fgercv5gnf0s4svmu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTm1IalV1cG10Tit4NVBu
            eUNSeDdleWhxdWpYdHhjVElwcDR1bkJORUNvCjAyVXJVTFZ1QktvRzhVVUV0dllC
            MndydEhzeE5BdmZyOE9kR3ZqWm9aTVkKLS0tIGZJVjA3YUFpb2dkNTc3eEdXWlJD
            RlFIZ3V1V0NFVGVTVjgzcGI5WmpibVEKmo/zGCAYnw8nf5lnLsJk9j6ERCNiFQA2
            gobFRSDWOOj0B3PVUKHNUXCqrJGQYzf3tYhE+6nGL9OnCuxA75aY7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-25T01:06:55Z"
    mac: ENC[AES256_GCM,data:K8PAEIWuZnCcwzlv7HbHTQcEOW85BzhU9K79lI5JchXVBIDYP521nGCQZQatRkER3dcer3co+txcewaJWCtYf4QWg6yxtC+qmk3+OEseukqwOqZbfq6BkWKByGWNdLXZ5yycTSGY4y+kDtuJkKfSAt6+RD3JR/DhGXxlqqLz0rM=,iv:MOm66uwK3Aff1SWyl/99iDCQSbsPOuYTzG2byHHPB34=,tag:KvLDNLHd5ZBBOm3Kikpc5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
