apiVersion: v1
kind: Service
metadata:
  name: zeus-lighthouse
  labels:
    app.kubernetes.io/name: lighthouse
    app.kubernetes.io/instance: zeus-lighthouse
    app.kubernetes.io/managed-by: zeus
spec:
  type: ClusterIP
  ports:
    - port: 9003
      targetPort: hercules
      protocol: TCP
      name: hercules
    - port: 9000
      targetPort: p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: 9000
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
    - port: 5052
      targetPort: http-api
      protocol: TCP
      name: http-api
    - port: 5054
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: lighthouse
    app.kubernetes.io/instance: zeus-lighthouse
